name: Server CI
on:
  push:
    branches:
      - main
    paths:
      - server/**
      - .github/workflows/ci-server.yaml
      - .github/workflows/_check-go.yaml
      - .github/workflows/_docker-go.yaml
  pull_request:
    paths:
      - server/**
      - .github/workflows/ci-server.yaml
      - .github/workflows/_check-go.yaml
      - .github/workflows/_docker-go.yaml
  workflow_dispatch:
  workflow_call:

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  ci:
    uses: curioswitch/go-curiostack/.github/workflows/export-go-server-ci.yaml@d8ad009d47b81cdf61e6c6bc1e0cbc483cba16ed
    with:
      project_dir: server
      service: catsearch-server
      deploy_dev: false
    secrets: inherit
